### ISSUE TITLE
As an organizer I want to make an expense claim

### ISSUE THREAD

**Issue by japsu** [con2/kompassi#347]
Implement first version of the expense claim form as a Survey.

- [ ] The receipt should be uploaded as a file upload field. See #346.
- [x] The expense claim form should require login. #327 
- [x] Expense claim status (NEW/APPROVED/PAID/REJECTED) should be represented as a dimension. #348 

[Blueprint](https://outline.con2.fi/doc/taloushallinto-6UhhJreExZ)
[Discussion on Slack](https://con2.slack.com/archives/C3ZGNGY48/p1705953140325369)
